// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDivadUjgS4nH3Tf4xSEYm2neF3lIX6VFs',
    appId: '1:307898410926:web:1a3d7f3c519ca83b0a4a3f',
    messagingSenderId: '307898410926',
    projectId: 'dating-test-app',
    authDomain: 'dating-test-app.firebaseapp.com',
    storageBucket: 'dating-test-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRCwCOqUONnEJwC5XV-MohwX07N_hG72E',
    appId: '1:307898410926:android:5fdb8e20897bf86c0a4a3f',
    messagingSenderId: '307898410926',
    projectId: 'dating-test-app',
    storageBucket: 'dating-test-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkv_ziqR4eMRxvdkTVDfpwMrlj0HN12Hg',
    appId: '1:307898410926:ios:b6890f81e8464cae0a4a3f',
    messagingSenderId: '307898410926',
    projectId: 'dating-test-app',
    storageBucket: 'dating-test-app.appspot.com',
    iosClientId: '307898410926-albdu23hnke35kdoi913aror1gif3uhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkv_ziqR4eMRxvdkTVDfpwMrlj0HN12Hg',
    appId: '1:307898410926:ios:b6890f81e8464cae0a4a3f',
    messagingSenderId: '307898410926',
    projectId: 'dating-test-app',
    storageBucket: 'dating-test-app.appspot.com',
    iosClientId: '307898410926-albdu23hnke35kdoi913aror1gif3uhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
